### PR TITLE
Add support for range queries on range fields

### PR DESCRIPTION
**Pull request by BradHolmes**
Hello,

First off, this is a wonderful little library and a huge help to our team as we consider adopting OpenSearch.   Thank you for providing this, and having such wonderful unit testing suite to boot!

In this PR, I have added support for range queries on ranged fields, at least to the extent that we currently have need.  If I missed something, I'd be happy to try to add support for it as well. 

I also took the liberty to refactor some of the comparison code so I could better understand it.  But I'm willing to undo that refactoring if is not consistent with the style of the project.

Thank you for your review and consideration!
-Brad

### CODE REVIEW

**Comment by BradHolmes** [comment]
I see I have left off a dependency change, which resulted in bumping the python version:

```
 [tool.poetry.dependencies]
-python = ">=3.8,<4"
+python = ">=3.9,<4"
 opensearch-py = "*"
 python-dateutil = "*"
+python-ranges = "^1.2.1"
 ```

@matthewdeanmartin : Are you ok with limiting openmock to `python >= 3.9` ?

**Comment by matthewdeanmartin** [comment]
looks good to me. The pyproject.toml has the python ver range that matters.

**Comment by BradHolmes** [comment]
I'm afraid that anyone who installs this package will get an error, because the dependency `python-ranges` will not be added to their environment.  

Also, I see this morning I left in a debug print statement on line 69.  

I'll open a new PR with those changes.

**Comment by BradHolmes** [comment]
Opened https://github.com/matthewdeanmartin/openmock/pull/5

**Comment by matthewdeanmartin** [comment]
This is finally pushed to [pypi](https://pypi.org/project/openmock/).

**Pull request merged**
